language: go

go:
  - 1.2
  - 1.3
  - tip

env:
  - LD_LIBRARY_PATH=$GOPATH/src/github.com/cloudescape/govix/vendor/libvix

install:
  - go get github.com/c4milo/unzipit
  - go get github.com/cloudescape/govix
  - go get github.com/dustin/go-humanize
  - go get github.com/hashicorp/terraform

matrix:
  allow_failures:
    - go: tip
