language: go

go:
  - 1.2
  - 1.3
  - tip

before_install:
  - go get github.com/c4milo/unzipit
  - mkdir -p $HOME/gopath/src/github.com/cloudescape/govix; git clone https://github.com/cloudescape/govix.git $HOME/gopath/src/github.com/cloudescape/govix
  - go get github.com/dustin/go-humanize
  - go get github.com/mitchellh/gox
  - mkdir -p $HOME/gopath/src/github.com/hashicorp/terraform; git clone https://github.com/hashicorp/terraform.git $HOME/gopath/src/github.com/hashicorp/terraform
  - export PATH="$HOME/gopath/bin:$PATH"
  - pushd $HOME/gopath/src/github.com/hashicorp/terraform; make dev; popd

install: make build

matrix:
  allow_failures:
    - go: tip
