language: go

go:
  - 1.2
  - 1.3
  - tip

install:
  - go get github.com/c4milo/unzipit
  - mkdir -p $GOPATH/src/github.com/cloudescape/govix; git clone https://github.com/cloudescape/govix.git $GOPATH/src/github.com/cloudescape/govix
  - go get github.com/dustin/go-humanize
  - mkdir -p $GOPATH/src/github.com/hashicorp/terraform; git clone https://github.com/hashicorp/terraform $GOPATH/src/github.com/hashicorp/terraform

matrix:
  allow_failures:
    - go: tip
